<a href="https://colab.research.google.com/github/victim1307/ai_club/blob/main/numpy/First.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Pratice**

In [2]:
import numpy as np #importing numpy

In [ ]:
list_1=[2,3,4,5]
print(list_1) #list

[2, 3, 4, 5]


In [ ]:
ary=np.array(list_1)
print(ary) # converting list to array

[2 3 4 5]


In [ ]:
x = np.array([1,2,6,9])
print(x) # defining array

[1 2 6 9]


In [ ]:
y=x+7
print(y) # adding int's

[ 8  9 13 16]


In [ ]:
print(x.shape) # shape of an array 
print(x.dtype) # dtype just defines how bytes in memory will be interpreted by a scalar

(4,)
int64


In [ ]:
z = np.array([(1,2,3,4),
              (4,5,6,8)])
print(z)

[[1 2 3 4]
 [4 5 6 8]]


In [ ]:
a=np.array([
    ((1,2,3,4),
    (5,6,7,8)),
    ((9,10,11,12),
     (13,14,15,16))
])
print(a.shape) 
#First 2 is dimension of the array
#Second 2 is no.of 2D arrays(it means 2X2)
#last elemrnt is to tell the  number of elements

(2, 2, 4)


In [ ]:
x=np.zeros((2,2),dtype=np.int16)
print(x)
#numpy.zeros(shape, dtype=float, order='C') defining

[[0 0]
 [0 0]]


In [ ]:
np.ones((2,3,4),dtype=np.int16)
#inner (2,3,4) 2X3 array with 4 elements

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
d=np.array([(1,2,3,4),(5,6,7,8)])
print(d)
d.reshape(4,2)
# numpy.reshape(a, newShape, order='C') Here,
# a: Array that you want to reshape
# newShape: The new desires shape

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
d.flatten()
#Converts into 1D array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x1=np.array([0,9,8,7])
x2=np.array([6,5,4,3])
print("Horizontal Append",np.hstack((x1,x2))) # appends 2 arrays horizantly
print("Vertical Append",np.vstack((x1,x2))) # appends 2 arrays vertically

Horizontal Append [0 9 8 7 6 5 4 3]
Vertical Append [[0 9 8 7]
 [6 5 4 3]]


In [ ]:
ran_arr=np.random.normal(8,0.0000008,7)
print(ran_arr)
# to generate random array 8 is the base value
# 0.0000008 is the range(Valuse will e in the range of 8-0.0000008 to 8+0.0000006)
# 7 is the number of elements in the list

[8.00000003 7.99999981 8.00000068 8.0000004  8.00000118 7.99999898
 7.99999948]


In [ ]:
A = np.matrix(np.ones((5,5))) # builds an array of 3X4 with all ones		
print(A)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[3]=2 # converts the whole column to desired int
print(A)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a3=np.arange(4,12) # intakes all the elements in the given range
print(a3)

[ 4  5  6  7  8  9 10 11]


In [ ]:
a4=np.arange(4,12,3) # intakes all the elements in the given range and the last elements will in sort of AP and d= the last digit 
print(a4)

[ 4  7 10]


In [ ]:
np.linspace(2.0, 8.0, num=20)
# Linspace gives evenly spaced samples.
# numpy.linspace(start, stop, num, endpoint)

array([2.        , 2.31578947, 2.63157895, 2.94736842, 3.26315789,
       3.57894737, 3.89473684, 4.21052632, 4.52631579, 4.84210526,
       5.15789474, 5.47368421, 5.78947368, 6.10526316, 6.42105263,
       6.73684211, 7.05263158, 7.36842105, 7.68421053, 8.        ])

In [ ]:
np.linspace(2.0, 8.0, num=20, endpoint=False)
#Endpoint: If True (default), stop is the last value. If False, stop value is not included.

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6,
       5.9, 6.2, 6.5, 6.8, 7.1, 7.4, 7.7])

In [ ]:
np.logspace(2.0,4.0,num=4)
#LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.
#numpy.logspace(start, stop, num, endpoint)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [ ]:
x = np.array([2,3,3], dtype=np.complex128)
x.itemsize

16

In [ ]:
e  = np.array([(1,2,3,4), (5,6,7,8)])
print("First",e[0])# slices first column
print("Second",e[1])# slices Second column
print("Second --1",e[:,1])
print("Second --1",e[1,:3])

First [1 2 3 4]
Second [5 6 7 8]
Second --1 [2 6]
Second --1 [5]


In [4]:
v=np.random.normal(8,0.0008,6)
print(np.min(v))
print(np.max(v))
print(np.mean(v))
print(np.median(v))
print(np.std(v))

7.999525154022651
8.000579287971743
8.000082044962447
8.000150265782498
0.0003763150097486675


In [9]:
h=[[1,2],[4,5]]
i=[[2,3],[6,7]]
np.matmul(h,i)

array([[14, 17],
       [38, 47]])

In [11]:
a=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(np.linalg.inv(a))

LinAlgError: ignored

In [19]:
det=np.linalg.det(a) # det calculator
rank=np.linalg.matrix_rank(a) # rank calculator
eigenvalues, eigenvectors = np.linalg.eig(a) # eigen values and matrix
diag=a.diagonal()
trans=a.transpose() # transpose
trac=a.trace()
print(eigenvalues, eigenvectors)
print(int(det))
print(int(rank))
print(diag)
print(trans)
print(trac)

[ 6.00000000e+00 -2.28386485e-16  0.00000000e+00] [[-0.26726124 -0.04554875 -0.31352117]
 [-0.53452248  0.72878003 -0.49613938]
 [-0.80178373 -0.68323128  0.80966054]]
0
1
[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
6
