<a href="https://colab.research.google.com/github/MANIKANTATHOTA23/AI-AMRITA/blob/main/NUMPY/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY IN DIFFERENT WAYS***

In [1]:
import numpy as np

**lists**

In [2]:
PythonList = [1,9,8,3]
print(PythonList)


[1, 9, 8, 3]


**NUMPY**

In [5]:
numpy_array = np.array(PythonList)
numpy_array

array([1, 9, 8, 3])

In [8]:
a = numpy_array+10
print(a)

[11 19 18 13]


In [10]:
a = np.array([1,5,9])
print(a)

[1 5 9]


In [11]:
b = a +10
print(b)

[11 15 19]


In [12]:
print(a.shape)
print(a.dtype)

(3,)
int64


In [13]:
c = np.array([(1,2,8,0),
              (4,5,6,1)])
print(c)

[[1 2 8 0]
 [4 5 6 1]]


In [16]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
      [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(2, 2, 3)


**TO PRINT 3 ROWS 3 COULMNS OF ZEROS**

In [17]:
x=np.zeros((3,3), dtype=np.int16)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


**TO PRINT 3 TIMES OF 2 ROWS 4 COLUMNS OF ONES**

In [21]:
y=np.ones((3,2,4), dtype=np.int16)
print(y)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


**RESHAPE TO 1 ELEMENT LISTS**

In [24]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(6,1)

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [35]:
print(e)

[[1 2 3]
 [4 5 6]]


In [36]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [37]:
print('Second column:', e[:,1])

Second column: [2 5]


In [38]:
print(e[1, :2])

[4 5]


In [25]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

**HORITONTAL AND VERTICAL STACK**

In [28]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print("Vertical append:")
print(np.vstack((f,g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical append:
[[1 2 3]
 [4 5 6]]


**TO FIND A LIST OF RANDOM ELEMENTS**

In [33]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.49238728 4.97669106 4.91951323 4.47986859 5.12593923 5.06817926
 5.2680344  4.35221261 4.66763552 4.55715104]


**FIND MIN , MAX, MEAN, MEDIAN,STD FROM A LISTS**

In [34]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

4.352212613229316
5.49238727930963
4.8907612207322115
4.948102144090097
0.34917526053989645


**TO PRINT ELEMENTS IN RANGE**

In [31]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [32]:
np.arange(1, 11,3)

array([ 1,  4,  7, 10])

In [39]:
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [41]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [40]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [42]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

**TO FIND DOT PRODUCT OF MATRIX**

In [43]:
f = np.array([1,2,3])
g = np.array([4,5,1])
### 1*4+2*5+3*1
np.dot(f, g)

17

**TO FIND THE INVERSE OF MATRIX**

In [44]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


**TO FIND THE MATRIX MULTIPLICATION**

In [45]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

**TO FIND THE DETERMINANT OF MATRIX**

In [46]:
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


**TO FIND THE RANK OF MATRIX**

In [47]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

**TO FIND THE TRANSPOSE OF THE MATRIX**

In [48]:
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


**TO FIND THE TRACE OF MATRIX**

In [49]:
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]


**TO FIND THE EIGEN VALUES AND EIGEN VECTORS OF MATRIX**

In [50]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]
